// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJEEKi3GGkbdkE3mA8egDWZAzP5wqaLRU',
    appId: '1:983076812844:web:fa67611055690d0a967989',
    messagingSenderId: '983076812844',
    projectId: 'flutter-finance-app-5f266',
    authDomain: 'flutter-finance-app-5f266.firebaseapp.com',
    storageBucket: 'flutter-finance-app-5f266.firebasestorage.app',
    measurementId: 'G-514GVHX59D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmeRXx95k9FLjQ1ihpuVi3AHh387T0g_Q',
    appId: '1:983076812844:android:ec651d9a3c5c6999967989',
    messagingSenderId: '983076812844',
    projectId: 'flutter-finance-app-5f266',
    storageBucket: 'flutter-finance-app-5f266.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFVu0C2vgOEzHFlkbKMJ6AZ4w64AL2AWY',
    appId: '1:983076812844:ios:004d1a3cdc879b0b967989',
    messagingSenderId: '983076812844',
    projectId: 'flutter-finance-app-5f266',
    storageBucket: 'flutter-finance-app-5f266.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFVu0C2vgOEzHFlkbKMJ6AZ4w64AL2AWY',
    appId: '1:983076812844:ios:004d1a3cdc879b0b967989',
    messagingSenderId: '983076812844',
    projectId: 'flutter-finance-app-5f266',
    storageBucket: 'flutter-finance-app-5f266.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJEEKi3GGkbdkE3mA8egDWZAzP5wqaLRU',
    appId: '1:983076812844:web:664831bcb59a487f967989',
    messagingSenderId: '983076812844',
    projectId: 'flutter-finance-app-5f266',
    authDomain: 'flutter-finance-app-5f266.firebaseapp.com',
    storageBucket: 'flutter-finance-app-5f266.firebasestorage.app',
    measurementId: 'G-GQLBDNQX6F',
  );
}
